version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "usuarios"
    ports:
      - "5430:5432"
    volumes:
      - /temp
